name: Terraform Destroy

on:
  workflow_dispatch:
    # Manual trigger only
    inputs:
      environment:
        description: "Environment to destroy"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - staging
          - production
      confirm_destroy:
        description: 'Type "DESTROY" to confirm infrastructure destruction'
        required: true

env:
  AWS_REGION: "us-east-1" # Set your AWS region
  TF_VAR_environment: ${{ github.event.inputs.environment }}

jobs:
  terraform-destroy:
    name: "Terraform Destroy"
    # Only proceed if proper confirmation is provided
    if: github.event.inputs.confirm_destroy == 'DESTROY'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        # Use AWS credentials for authentication (OIDC recommended for production)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 # Specify your desired Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        # Show the destroy plan first for visibility
        run: terraform plan -destroy -out=tfdestroyplan

      - name: Terraform Destroy
        # Auto-approve is acceptable for a manually triggered destroy after confirmation
        run: terraform destroy --auto-approve
